<a href="https://colab.research.google.com/github/FernandoMV1/DS1--Python/blob/main/Tarea_1_Fernando_Miguel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Para completar esta tarea deberá crear una copia de este cuaderno de trabajo en su Google Drive, luego compartir el link publicamente y subirlo a moodle.

# Incluir Numpy
Usando la funcion import, declare la librería Numpy como np recuerde que solamente debe hacerlo una vez en su cuaderno

In [ ]:
import numpy as np

# Declaración de Variables
Para cada una de las matrices presentadas, declarelas dentro de una variable en python

$$
A = \begin{pmatrix}
1 & 2\\
3 & 4
\end{pmatrix}
$$


In [ ]:
A = np.matrix ([[1,2],[3,4]])
A

matrix([[1, 2],
        [3, 4]])


$$
B = \begin{pmatrix}
5 & 6\\
7 & 8
\end{pmatrix}
$$


In [ ]:
B = np.matrix ([[5,6],[7,8]])
B

matrix([[5, 6],
        [7, 8]])


$$
C = \begin{pmatrix}
-1 & 0\\
2 & 3
\end{pmatrix}
$$


In [ ]:
C = np.matrix ([[-1,0],[2,3]])
C

matrix([[-1,  0],
        [ 2,  3]])


$$
D = \begin{pmatrix}
2 & -3\\
-4 & 5
\end{pmatrix}
$$


In [ ]:
D = np.matrix ([[2,-3],[-4,5]])
D

matrix([[ 2, -3],
        [-4,  5]])


$$
E = \begin{pmatrix}
0 & 1\\
1 & 0
\end{pmatrix}
$$


In [ ]:
E = np.matrix ([[0,1],[1,0]])
E

matrix([[0, 1],
        [1, 0]])


$$
F = \begin{pmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{pmatrix}
$$


In [ ]:
F = np.matrix ([[1,2,3],[4,5,6],[7,8,9]])
F

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


$$
G = \begin{pmatrix}
-2 & 0 & 1\\
3 & -1 & 2\\
0 & 4 & 5
\end{pmatrix}
$$


In [ ]:
G = np.matrix ([[-2,0,1],[3,-1,2],[0,4,5]])
G

matrix([[-2,  0,  1],
        [ 3, -1,  2],
        [ 0,  4,  5]])


$$
H = \begin{pmatrix}
1 & 2 & -1\\
-3 & 0 & 4\\
2 & -1 & 2
\end{pmatrix}
$$


In [ ]:
H = np.matrix ([[1,2,-1],[-3,0,4],[2,-1,2]])
H

matrix([[ 1,  2, -1],
        [-3,  0,  4],
        [ 2, -1,  2]])


$$
I = \begin{pmatrix}
0 & 1 & 0\\
0 & 0 & 1\\
1 & 0 & 0
\end{pmatrix}
$$


In [ ]:
I = np.matrix ([[0,1,0],[0,0,1],[1,0,0]])
I

matrix([[0, 1, 0],
        [0, 0, 1],
        [1, 0, 0]])


$$
J = \begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$$

In [ ]:
J = np.matrix ([[1,0,0],[0,1,0],[0,0,1]])
J

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

# Suma de Matrices




Dadas las matrices $A$  y $C$ , calcule la matriz resultante de la suma $A$+$C$

In [ ]:
A + C

matrix([[0, 2],
        [5, 7]])



Dadas las matrices $B$  y $F$ , calcule la matriz resultante de la suma $B$+$F$


In [ ]:
B + F

ValueError: ignored

!!!!!!!Las matrices **no son del mismo tamano** por eso no se puee realizar la suma

---





Dadas las matrices $D$ y $I$, calcule la matriz resultante de la suma $D$+$I$ *$D$

In [ ]:
D + I


ValueError: ignored

!!!!!!!Las matrices **no son del mismo tamano** por eso no se puee realizar la suma




Dadas las matrices $E$ y $H$ , calcule la matriz resultante de la suma $E$+$H$

In [ ]:
E + H

ValueError: ignored

!!!!!!!Las matrices **no son del mismo tamano** por eso no se puee realizar la suma



Dadas las matrices $G$  y $J$ , calcule la matriz resultante de la suma $G$+$J$

In [ ]:
G + J

matrix([[-1,  0,  1],
        [ 3,  0,  2],
        [ 0,  4,  6]])

# Resta de Matrices

Dadas las matrices $A$
 y $D$
, calcule la matriz resultante de la resta $A$−$D$



In [ ]:
A-D

matrix([[-1,  5],
        [ 7, -1]])

Dadas las matrices $B$
 y $G$
, calcule la matriz resultante de la resta $B$−$G$


In [ ]:
B-G

ValueError: ignored

!!!!!!!Las matrices **no son del mismo tamano** por eso no se puee realizar la resta


Dadas las matrices $C$
 y $F$
, calcule la matriz resultante de la resta $C$−$F$


In [ ]:
C-F

ValueError: ignored

!!!!!!!Las matrices **no son del mismo tamano** por eso no se puee realizar la resta

Dadas las matrices $E$
 y $I$
, calcule la matriz resultante de la resta $E$−$I$


In [ ]:
E-I

ValueError: ignored

!!!!!!!Las matrices **no son del mismo tamano** por eso no se puee realizar la resta


Dadas las matrices $H$
 y $J$
, calcule la matriz resultante de la resta H−J

In [ ]:
H-J

matrix([[ 0,  2, -1],
        [-3, -1,  4],
        [ 2, -1,  1]])

#multiplicación de matrices

Dadas las matrices $A$
 y $D$
, calcule la matriz resultante de la multiplicación $A$⋅$D$




In [ ]:
A * D

matrix([[ -6,   7],
        [-10,  11]])

Dadas las matrices $B$
 y $E$
, calcule la matriz resultante de la multiplicación $B$⋅$E$



In [ ]:
B*E

matrix([[6, 5],
        [8, 7]])

Dadas las matrices $C$
 y $G$
, calcule la matriz resultante de la multiplicación $C$⋅$G$


In [ ]:
C*G

ValueError: ignored

!!!!!!! La multiplicación no puede ser realizada porque el número de filas de la primera matriz no es igual al número de columnas de la segunda matriz


Dadas las matrices $F$
 y $I$
, calcule la matriz resultante de la multiplicación $F$⋅$I$


In [ ]:
F*I

matrix([[3, 1, 2],
        [6, 4, 5],
        [9, 7, 8]])


Dadas las matrices $H$
 y $J$
, calcule la matriz resultante de la multiplicación $H$⋅$J$

In [ ]:
H*J

matrix([[ 1,  2, -1],
        [-3,  0,  4],
        [ 2, -1,  2]])

Dada la matriz $B$
, calcule la matriz resultante de la multiplicación por un escalar (−3)$B$


In [ ]:
-3*B

matrix([[-15, -18],
        [-21, -24]])


Dada la matriz $C$
, calcule la matriz resultante de la multiplicación por un escalar 5$C$



In [ ]:
5*C

matrix([[-5,  0],
        [10, 15]])

Dada la matriz $E$
, calcule la matriz resultante de la multiplicación por un escalar (−2)$E$


In [ ]:
-2*E

matrix([[ 0, -2],
        [-2,  0]])


Dada la matriz $G$
, calcule la matriz resultante de la multiplicación por un escalar 4$G$


In [ ]:
4*G

matrix([[-8,  0,  4],
        [12, -4,  8],
        [ 0, 16, 20]])


Dada la matriz $J$
, calcule la matriz resultante de la multiplicación por un escalar (−1)$J$4

In [ ]:
-1*J*4

matrix([[-4,  0,  0],
        [ 0, -4,  0],
        [ 0,  0, -4]])

# potenciación de matrices

Dada la matriz $A$
, calcule la matriz resultante de la potencia $A$<sup>3



In [ ]:
A**3

matrix([[ 37,  54],
        [ 81, 118]])


Dada la matriz $C$
, calcule la matriz resultante de la potencia $C$<sup>2



In [ ]:
C**2

matrix([[1, 0],
        [4, 9]])

Dada la matriz $D$
, calcule la matriz resultante de la potencia $D$<sup>3



In [ ]:
D**3

matrix([[ 116, -153],
        [-204,  269]])

Dada la matriz $G$
, calcule la matriz resultante de la potencia $G$<sup>2

In [ ]:
G**2

matrix([[ 4,  4,  3],
        [-9,  9, 11],
        [12, 16, 33]])

Dada la matriz $J$
, calcule la matriz resultante de la potencia $J$<sup>4


In [ ]:
J**4

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

# Solución de ecuaciones lineales

La función numpy.linalg.solve() resuelve sistemas de ecuaciones lineales de la forma Ax=b
, donde A
 es una matriz cuadrada y b
 es un vector columna. A continuación te presento los vectores columna que utilizaras para los ejercicios de esta sección

 $b_1 = \begin{pmatrix} 3 \ 5 \end{pmatrix}$

 $b_2 = \begin{pmatrix} 1 \ 2  \end{pmatrix}$

 $b_3 = \begin{pmatrix} 4 \ 7  \end{pmatrix}$

 $b_4 = \begin{pmatrix} 2 \ 1 \ 4 \end{pmatrix}$

 $b_5 = \begin{pmatrix} 6 \ 2 \ 3 \end{pmatrix}$

Dada la matriz $A$
 y el vector columna $b_1$
, resuelve el sistema de ecuaciones lineales $Ax_1=b_1$




In [ ]:
b_1 = np.matrix ([[3],[5]])
x_1=np.linalg.solve(A,b_1)
x_1

matrix([[-1.],
        [ 2.]])

Realice la comprobación

In [ ]:
A*x_1

matrix([[3.],
        [5.]])

Dada la matriz $B$
 y el vector columna $b_2$
, resuelve el sistema de ecuaciones lineales $Bx_2=b_2$


In [ ]:
b_2 = np.matrix ([[1],[2]])
x_2=np.linalg.solve(B,b_2)
x_2

matrix([[ 2. ],
        [-1.5]])

Realice la comprobación

In [ ]:
B*x_2

matrix([[1.],
        [2.]])


Dada la matriz $C$
 y el vector columna $b_3$
, resuelve el sistema de ecuaciones lineales $Cx_3=b_3$


In [ ]:
b_3 = np.matrix ([[4],[7]])
x_3=np.linalg.solve(C,b_3)
x_3

matrix([[-4.],
        [ 5.]])

Realice la comprobación

In [ ]:
C*x_3

matrix([[4.],
        [7.]])


Dada la matriz $F$
 y el vector columna $b_4$
, resuelve el sistema de ecuaciones lineales $Fx_4=b_4$


In [ ]:
b_4 = np.matrix([[2],[1],[4]])
x_4 = np.linalg.solve(F,b_4)
x_4

LinAlgError: ignored

In [ ]:
np.linalg.det(F)

0.0

!!!!!!!Como el determinante de esta matriz es 0, es imposible realizar la operación.

Realice la comprobación


Dada la matriz $J$
 y el vector columna $b_5$
, resuelve el sistema de ecuaciones lineales $Jx_5=b_5$

In [ ]:
b_5 = ([[6],[2],[3]])
x_5=np.linalg.solve(J,b_5)
x_5

array([[6.],
       [2.],
       [3.]])

Realice la comprobación

In [ ]:
J*x_5

matrix([[6.],
        [2.],
        [3.]])