<a href="https://colab.research.google.com/github/FernandoMV1/DS1--Python/blob/main/Tarea_2_Linear_Algebra%2C_Statistics%2C_Conclusions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importa Numpy

In [ ]:
import numpy as np

# Operaciones con np.array

Para cada una de las matrices presentadas, declarelas dentro de una variable array en python

$$
A = \begin{pmatrix}
3 & 6 & 9\\
2 & 5 & 8\\
1 & 4 & 7
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
2 & 6 & 9\\
8 & 5 & 3\\
5 & 0 & 7
\end{pmatrix}
$$

$$
C = \begin{pmatrix}
3 & 6 & 9\\
1 & 2 & 4\\
6 & 4 & 9
\end{pmatrix}
$$

$$
D = \begin{pmatrix}
9 & 9 & -9\\
3 & -2 & 7\\
5 & 4 & -8
\end{pmatrix}
$$

In [ ]:
A = np.array([[3,6,9],[2,5,8],[1,4,7]])
A

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [ ]:
B = np.array([[2,6,9],[8,5,3],[5,0,7]])
B

array([[2, 6, 9],
       [8, 5, 3],
       [5, 0, 7]])

In [ ]:
C = np.array([[3,6,9],[1,2,4],[6,4,9]])
C

array([[3, 6, 9],
       [1, 2, 4],
       [6, 4, 9]])

In [ ]:
D = np.array([[9,9,-9],[3,-2,7],[5,4,-8]])
D

array([[ 9,  9, -9],
       [ 3, -2,  7],
       [ 5,  4, -8]])

## Multiplica:
$$A*C$$
$$B*D$$
$$D*A$$
$$A*A$$


In [ ]:
A @ C

array([[ 69,  66, 132],
       [ 59,  54, 110],
       [ 49,  42,  88]])

In [ ]:
B @ D

array([[  81,   42,  -48],
       [ 102,   74,  -61],
       [  80,   73, -101]])

In [ ]:
D @ A

array([[36, 63, 90],
       [12, 36, 60],
       [15, 18, 21]])

In [ ]:
A @ A

array([[ 30,  84, 138],
       [ 24,  69, 114],
       [ 18,  54,  90]])

## Eleva:
$$A^2$$
$$B^4$$
$$D^3$$
$$C^2$$

In [ ]:
np.linalg.matrix_power(A,2)

array([[ 30,  84, 138],
       [ 24,  69, 114],
       [ 18,  54,  90]])

In [ ]:
np.linalg.matrix_power(B,4)

array([[16846, 10110, 23445],
       [16930, 11551, 25065],
       [10725,  6900, 16531]])

In [ ]:
np.linalg.matrix_power(D,3)

array([[ 918,  729, -810],
       [ 196,   -2,  685],
       [ 403,  331, -494]])

In [ ]:
np.linalg.matrix_power(C,2)

array([[ 69,  66, 132],
       [ 29,  26,  53],
       [ 76,  80, 151]])

# Algebra lineal 2

## Crea una matriz identidad de 6x6

In [ ]:
np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Calcula la inversa de las matrices declaradas

In [ ]:
Ainv = np.linalg.inv(A)
Ainv

LinAlgError: ignored

In [ ]:
Adet = np.linalg.det(A)
Adet

0.0

In [ ]:
Binv = np.linalg.inv(B)
Binv

array([[-0.0872818 ,  0.10473815,  0.06733167],
       [ 0.10224439,  0.07730673, -0.16458853],
       [ 0.06234414, -0.07481297,  0.09476309]])

In [ ]:
Cinv = np.linalg.inv(C)
Cinv

array([[ 8.33333333e-02, -7.50000000e-01,  2.50000000e-01],
       [ 6.25000000e-01, -1.12500000e+00, -1.25000000e-01],
       [-3.33333333e-01,  1.00000000e+00,  2.77555756e-17]])

In [ ]:
Dinv = np.linalg.inv(D)
Dinv

array([[-0.05333333,  0.16      ,  0.2       ],
       [ 0.26222222, -0.12      , -0.4       ],
       [ 0.09777778,  0.04      , -0.2       ]])

## Transpone las matrices inversas generadas en el punto anterior

In [ ]:
Btran = np.transpose(Binv)
Btran

array([[-0.0872818 ,  0.10224439,  0.06234414],
       [ 0.10473815,  0.07730673, -0.07481297],
       [ 0.06733167, -0.16458853,  0.09476309]])

In [ ]:
Ctran = np.transpose(Cinv)
Ctran

array([[ 8.33333333e-02,  6.25000000e-01, -3.33333333e-01],
       [-7.50000000e-01, -1.12500000e+00,  1.00000000e+00],
       [ 2.50000000e-01, -1.25000000e-01,  2.77555756e-17]])

In [ ]:
Dtran = np.transpose(Dinv)
Dtran

array([[-0.05333333,  0.26222222,  0.09777778],
       [ 0.16      , -0.12      ,  0.04      ],
       [ 0.2       , -0.4       , -0.2       ]])

## Resuelve los siguientes sistemas de ecuación lineal
asegurate de declarar las variables primero

$$2x + y - 3z = 4$$
$$x - 3y + 2z = -1$$
$$4x + 2y + z = 7$$

In [ ]:
Ae = np.array([[2,1,-3],[1,-3,2],[4,2,1]])
Ae

array([[ 2,  1, -3],
       [ 1, -3,  2],
       [ 4,  2,  1]])

In [ ]:
ae = np.array([[4],[-1],[7]])
ae

array([[ 4],
       [-1],
       [ 7]])

In [ ]:
xae = np.linalg.solve(Ae,ae)
xae

array([[ 1.42857143],
       [ 0.71428571],
       [-0.14285714]])

## Verificación

In [ ]:
Ae @ xae

array([[ 4.],
       [-1.],
       [ 7.]])

$$2x + y - 3z + 4w = 10$$
$$x - 3y + 2z - w = 5$$
$$4x + 2y + z + 2w = 17$$
$$3x + y + 5z - w = 8$$

In [ ]:
Be = np.array([[2,1,-3,4],[1,-3,2,-1],[4,2,1,2],[3,1,5,-1]])
Be

array([[ 2,  1, -3,  4],
       [ 1, -3,  2, -1],
       [ 4,  2,  1,  2],
       [ 3,  1,  5, -1]])

In [ ]:
be = np.array([[10],[5],[17],[8]])
be

array([[10],
       [ 5],
       [17],
       [ 8]])

In [ ]:
xbe = np.linalg.solve(Be,be)
xbe

array([[ 6.53571429],
       [-0.42857143],
       [-2.78571429],
       [-2.75      ]])

##Verificacíon

In [ ]:
Be @ xbe

array([[10.],
       [ 5.],
       [17.],
       [ 8.]])

# Estadística Descriptiva

Importa Pandas como pd

In [ ]:
import pandas as pd

Descarga el set de datos costumers-dataset de kagle
https://www.kaggle.com/datasets/datascientistanna/customers-dataset

Guardalo en tu Google Drive e Importa el documento a Google Colaboratory

In [ ]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive


Crea un Dataframe de Pandas

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Kodigo Bootcamp/Customers2.csv')

In [ ]:
df

CustomerID  Gender  Age  Annual_Income  Spending_Score     Profession  \
0              1    Male   19          15000              39     Healthcare   
1              2    Male   21          35000              81       Engineer   
2              3  Female   20          86000               6       Engineer   
3              4  Female   23          59000              77         Lawyer   
4              5  Female   31          38000              40  Entertainment   
...          ...     ...  ...            ...             ...            ...   
1995        1996  Female   71         184387              40         Artist   
1996        1997  Female   91          73158              32         Doctor   
1997        1998    Male   87          90961              14     Healthcare   
1998        1999    Male   77         182109               4      Executive   
1999        2000    Male   90         110610              52  Entertainment   

      Work_Experience  Family_Size  
0                   1            4  
1                   3            3  
2                   1            1  
3                   0            2  
4                   2            6  
...               ...          ...  
1995                8            7  
1996                7            7  
1997                9            2  
1998                7            2  
1999                5            2  

[2000 rows x 8 columns]

## Calcula todas las medidas de tendencia central para 1 variable numérica y una categórica

In [ ]:
df.Annual_Income.mean()

110731.8215

In [ ]:
df.Annual_Income.median()

110045.0

In [ ]:
df.Annual_Income.value_counts()

50000     7
9000      7
97000     6
85000     6
4000      6
         ..
111859    1
186655    1
164598    1
132951    1
110610    1
Name: Annual_Income, Length: 1786, dtype: int64

In [ ]:
df.Annual_Income.mode()

0     9000
1    50000
Name: Annual_Income, dtype: int64

In [ ]:
df.Profession.value_counts()

Artist           612
Healthcare       339
Entertainment    234
Engineer         179
Doctor           161
Executive        153
Lawyer           142
Marketing         85
Homemaker         60
Name: Profession, dtype: int64

In [ ]:
df.Profession.mode()

0    Artist
Name: Profession, dtype: object

## Crea una tabla cruzada para dos variables

In [ ]:
pd.crosstab(df.Gender,df.Profession)

Profession  Artist  Doctor  Engineer  Entertainment  Executive  Healthcare  \
Gender                                                                       
Female         380      89       103            133         87         196   
Male           232      72        76            101         66         143   

Profession  Homemaker  Lawyer  Marketing  
Gender                                    
Female             39      86         53  
Male               21      56         32

## Calcula la media para una variable numérica aplicando condiciones de O y de Y de dos variables

Deberás presentar un ejercicio y y uno O

In [ ]:
df[(df.Profession=='Engineer')&(df.Age>45)].Annual_Income.mean()

112151.51785714286

In [ ]:
df[(df.Profession=='Engineer')|(df.Age>45)].Annual_Income.mean()

111699.23550401427

## Utiliza Percentiles

Crea una tabla que presente el percentil enesimo (elegelo tu) por cada categoría

In [ ]:
df.Annual_Income.quantile([0.9])

0.9    173051.4
Name: Annual_Income, dtype: float64

In [ ]:
df.Spending_Score.quantile([0.9])

0.9    90.0
Name: Spending_Score, dtype: float64

## Explora los datos

Identifica el comportamiento interesante de una variable categórica (Usando media, moda, percentiles etc) y escribe en tus palabras la razón que crees variable se comporta así

In [ ]:
Profesion_sueldo = df.groupby(df.Profession).Annual_Income.mean()
Profesion_sueldo

Profession
Artist           108776.580065
Doctor           111573.217391
Engineer         111161.240223
Entertainment    110650.333333
Executive        113770.130719
Healthcare       112574.041298
Homemaker        108758.616667
Lawyer           110995.838028
Marketing        107994.211765
Name: Annual_Income, dtype: float64

In [ ]:
Profesion_sueldo.sort_values(ascending=False)

Profession
Executive        113770.130719
Healthcare       112574.041298
Doctor           111573.217391
Engineer         111161.240223
Lawyer           110995.838028
Entertainment    110650.333333
Artist           108776.580065
Homemaker        108758.616667
Marketing        107994.211765
Name: Annual_Income, dtype: float64

In [ ]:
Profesion_sueldo.quantile(0.9)

112813.25918213894

In [ ]:
Profesion_sueldo.quantile(0.5)

110995.83802816902

In [ ]:
Profesion_edad = df.groupby(df.Profession).Age.mean()
Profesion_edad

Profession
Artist           49.004902
Doctor           46.621118
Engineer         55.094972
Entertainment    51.162393
Executive        46.601307
Healthcare       47.843658
Homemaker        45.366667
Lawyer           47.753521
Marketing        45.823529
Name: Age, dtype: float64

In [ ]:
Profesion_edad.sort_values(ascending=False)

Profession
Engineer         55.094972
Entertainment    51.162393
Artist           49.004902
Healthcare       47.843658
Lawyer           47.753521
Doctor           46.621118
Executive        46.601307
Marketing        45.823529
Homemaker        45.366667
Name: Age, dtype: float64

Los ejecutivos son los que reciben los sueldos mas grandes a pesar que no son los que en promedio tienen más edad. Esto se debe a que tienen puestos importantes y sus aumentos se basan más por su experiencia laboral que por sus estudios.
Al contrario, ejemplos como los artistas con trabajos menos estables se explica porque ni siquiera entran en el 50% de los que ganan más. A pesar que sean los que en promedio tengan más años de edad, su trabajo no es tan crucial como el de un ejecutivo y además se necesita mucha perfección de la técnica, por eso tantos años.
Si hago un estudio por ejemplo sobre que recomendaría estudiar para obtener éxito más rapidamente, optaría por ser ejecutivo: Menos tiempo a mejor salario.